kind: Secret
apiVersion: v1
metadata:
  name: es-users-file-realm
stringData:
  users: |-
{{- range $user, $password := .Values.users }}
    {{ $user }}:{{ $password }}
{{- end  }}
  users_roles: |-
{{- range $userroles, $role := .Values.user_roles }}
    {{ $userroles }}:{{ $role }}
{{- end  }}