users:
    filebeat: ENC[AES256_GCM,data:Z6cnV/sNDUY0qog7VHRWlg==,iv:e3+0eRvs0Kr571J4FpQsaztyQYb/NI0899JYjTksFtA=,tag:S0X55ktsCJjiBF+gRHRZKQ==,type:str]
user_roles:
    kibana_admin: ENC[AES256_GCM,data:etB8n1UCghs=,iv:JVUvS+eIjZhNYZIKVmvNbOgWb1qzkRzifcMeMK7WENE=,tag:TAzts57YWskuGwuY0T9N8Q==,type:str]
    ingest_admin: ENC[AES256_GCM,data:h9KXLg1dc8U=,iv:ZsVwBa5fsdnTKwI48J3sMlcYdWkvEBl42mFHxNh01X8=,tag:h9GmITpXE++u/BguIVJE0w==,type:str]
    superuser: ENC[AES256_GCM,data:DZ/0rF84HII=,iv:kifBRtDPtAkTkSGLoIll5Q+XoDbp7suJOPuaPXnhD+0=,tag:92sT+7T15H8bo5kI1hc8yg==,type:str]
    beats_admin: ENC[AES256_GCM,data:6r6o2lLbI8M=,iv:hziqbfm3Bn2edRjywaeLDNOcaD5fdCG+4IJd5336jC8=,tag:HriDgvN/aCXHUgVjJXOaSQ==,type:str]
    data_frame_transforms_admin: ENC[AES256_GCM,data:czVZbv2jCrQ=,iv:VgmgIhIMfhSIQ5kx4jYOrYzJqTX8KjSDxc7/UeYVg5Q=,tag:nLMusWszd6ceVWLXC050vg==,type:str]
    transform_admin: ENC[AES256_GCM,data:tIvIL3Z38TY=,iv:WBl7QwXIyRoAL3pm681IPBgQzogxlu+2Jvm9Jv+QvVU=,tag:1sTkH1fu3Kd2O0P6EobfOg==,type:str]
    viewer: ENC[AES256_GCM,data:S6W5nN/bLjY=,iv:sIAo4CgvC26TMz9dkWK0bIrW/GEdjNJZ2p9YEXP3MeE=,tag:qDiEr03unFAc/Hj7yrpUNQ==,type:str]
    admin: ENC[AES256_GCM,data:zbUJUjOEmP4=,iv:WFGrOvGn7o1QMOOgrJANKUjNgkrhj49mEzRiqFjxOXM=,tag:kQ8KVYiRqnlqoxvAijeGeQ==,type:str]
filebeat:
    envVars:
        ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:4pOxZIGz6QizgjHVjSbdUQ==,iv:4g1BGFtI21parPF7fJcQ7D+QRKRyZfeM2sU21Uo0ZJQ=,tag:hL/uBmH1rj8BBAir/8pZtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uy0a2he4tw02cwelyfdmztjrdksrll7mc6lup7sgaxya77accc7s8s796y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTWhIWlAzZXpqTmhFcWlC
            SmxDNzBVRkprUk1obWp0bTdBK25KL3FHa1hrCkZaTEFwRUpFU05xbWxTTEhwUm80
            K1V1eHFpU3E1ajMraGJnMXM0NmZWVDgKLS0tIDhQcklkSXcrRWVVb0UreEJHd3VW
            SWhheGo0TG1JbkRDWmtvblh5dDNPeWsKM7Y84ndq9Rxsm91jzMNbh9mRLfUIL18i
            O06zPvIXJkBzoU1VzykBQZhhQa8Horz7U2/VE/G+pqoSKQXdINuKEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-04T09:59:08Z"
    mac: ENC[AES256_GCM,data:sfXDrLsjN3IRe9/jvBmSyUMT4z7CMjESM1JbBJxneoou0pq7orSOXVWsSUnkt75ZRGpHihn4+H6cEPXzMXKWy0ulEX75QyYA6JMxNp6qi6a7XNkfYUDwHFcdaFBbulwYMzk8VWDgYDqYFc9wlns9K8hlq2ESwIyCw1mQelsBZCM=,iv:VIrjn55CqOTazA6NERNMeuMaqJbNtjAiMLdP2a5D9v8=,tag:lioDLCVNI0bBTktHVU5VuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
